// <auto-generated />
using System;
using GEORGE.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GEORGE.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250305104344_InitialMigration51")]
    partial class InitialMigration51
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GEORGE.Shared.Models.ElemetZamDoZlecen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CenaNetto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CzyZamowiono")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataDostarczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Dlugosc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("IloscSztuk")
                        .HasColumnType("float");

                    b.Property<string>("Jednostka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kolor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerKatalogowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Objetosc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Powierzchnia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PozDostarczono")
                        .HasColumnType("bit");

                    b.Property<string>("RowIdPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdPlikuDodatkowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdProducent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZlecenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Szerokosc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Waga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Wysokosc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ElemetZamDoZlecen");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.KantowkaDoZlecen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataDostarczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("DlugoscNaGotowo")
                        .HasColumnType("int");

                    b.Property<string>("DlugoscNaGotowoGrupa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DlugoscZamawiana")
                        .HasColumnType("int");

                    b.Property<string>("GatunekKantowki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IloscSztuk")
                        .HasColumnType("int");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaterialZeStanMagazyn")
                        .HasColumnType("bit");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PozDostarczono")
                        .HasColumnType("bit");

                    b.Property<string>("Przekroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZlecenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WyslanoDoZamowien")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KantowkaDoZlecen");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.KartyInstrukcyjne", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("IloscStron")
                        .HasColumnType("int");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkDoKartyNaSerwerze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerKarty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisKarty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KartyInstrukcyjne");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.KonfModele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("DodatkowyFiltrWystepowania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KatWystapieniaZakresOdMax")
                        .HasColumnType("int");

                    b.Property<int?>("KatWystapieniaZakresOdMin")
                        .HasColumnType("int");

                    b.Property<int?>("KonstrMaxSzer")
                        .HasColumnType("int");

                    b.Property<int?>("KonstrMaxWys")
                        .HasColumnType("int");

                    b.Property<int?>("KonstrMinSzer")
                        .HasColumnType("int");

                    b.Property<int?>("KonstrMinWys")
                        .HasColumnType("int");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaKonfiguracji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PromienWystapieniaZakresOdMax")
                        .HasColumnType("int");

                    b.Property<int?>("PromienWystapieniaZakresOdMin")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RowIdElement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RowIdSystem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Rysunek")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KonfModele");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.KonfSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Cena1MB")
                        .HasColumnType("float");

                    b.Property<double?>("Cena1MBKantowki1")
                        .HasColumnType("float");

                    b.Property<double?>("Cena1MBKantowki2")
                        .HasColumnType("float");

                    b.Property<double?>("Cena1MBKantowki3")
                        .HasColumnType("float");

                    b.Property<double?>("Cena1MBKantowki4")
                        .HasColumnType("float");

                    b.Property<double?>("Cena1MBKantowki5")
                        .HasColumnType("float");

                    b.Property<bool>("CzyMozeBycFix")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DlugoscKantowki1")
                        .HasColumnType("float");

                    b.Property<double?>("DlugoscKantowki2")
                        .HasColumnType("float");

                    b.Property<double?>("DlugoscKantowki3")
                        .HasColumnType("float");

                    b.Property<double?>("DlugoscKantowki4")
                        .HasColumnType("float");

                    b.Property<double?>("DlugoscKantowki5")
                        .HasColumnType("float");

                    b.Property<string>("DodatkowyFiltrWystepowania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("IloscSztukKantowki1")
                        .HasColumnType("float");

                    b.Property<double?>("IloscSztukKantowki2")
                        .HasColumnType("float");

                    b.Property<double?>("IloscSztukKantowki3")
                        .HasColumnType("float");

                    b.Property<double?>("IloscSztukKantowki4")
                        .HasColumnType("float");

                    b.Property<double?>("IloscSztukKantowki5")
                        .HasColumnType("float");

                    b.Property<string>("Indeks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KatWystapieniaZakresOdMax")
                        .HasColumnType("int");

                    b.Property<int?>("KatWystapieniaZakresOdMin")
                        .HasColumnType("int");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PionDodatkowa4")
                        .HasColumnType("int");

                    b.Property<int?>("PionDodatkowa5")
                        .HasColumnType("int");

                    b.Property<int?>("PionLewa")
                        .HasColumnType("int");

                    b.Property<int?>("PionOdSzybaOdZew")
                        .HasColumnType("int");

                    b.Property<int?>("PionPrawa")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomDodatkowa6")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomDodatkowa7")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomDol")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomGora")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomKorpus")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomLiniaOkucia")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomLiniaSzkla")
                        .HasColumnType("int");

                    b.Property<int?>("PoziomOsDormas")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RowIdSystem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Rysunek")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SVG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Waga")
                        .HasColumnType("float");

                    b.Property<double?>("WagaKantowki1")
                        .HasColumnType("float");

                    b.Property<double?>("WagaKantowki2")
                        .HasColumnType("float");

                    b.Property<double?>("WagaKantowki3")
                        .HasColumnType("float");

                    b.Property<double?>("WagaKantowki4")
                        .HasColumnType("float");

                    b.Property<double?>("WagaKantowki5")
                        .HasColumnType("float");

                    b.Property<int?>("WymiarXKantowki1")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarXKantowki2")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarXKantowki3")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarXKantowki4")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarXKantowki5")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarYKantowki1")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarYKantowki2")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarYKantowki3")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarYKantowki4")
                        .HasColumnType("int");

                    b.Property<int?>("WymiarYKantowki5")
                        .HasColumnType("int");

                    b.Property<bool>("WystepujeDol")
                        .HasColumnType("bit");

                    b.Property<bool>("WystepujeGora")
                        .HasColumnType("bit");

                    b.Property<bool>("WystepujeLewa")
                        .HasColumnType("bit");

                    b.Property<bool>("WystepujePrawa")
                        .HasColumnType("bit");

                    b.Property<int?>("ZakresStosDlugoscOdMax")
                        .HasColumnType("int");

                    b.Property<int?>("ZakresStosDlugoscOdMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KonfSystem");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.LinieProdukcyjne", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("DziennaZdolnoscProdukcyjna")
                        .HasColumnType("int");

                    b.Property<string>("IdLiniiProdukcyjnej")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaLiniiProdukcyjnej")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LinieProdukcyjne");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.Logowania", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Datalogowania")
                        .HasColumnType("datetime2");

                    b.Property<string>("RodzajPrzegladarki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uzytkownik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logowania");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.PlikiZlecenProdukcyjnych", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OryginalnaNazwaPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZleceniaProdukcyjne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WidocznyDlaWszystkich")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PlikiZlecenProdukcyjnych");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.PozDoZlecen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Ciezar1Sztuki")
                        .HasColumnType("real");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("IloscOkien")
                        .HasColumnType("int");

                    b.Property<int>("Iloscskrzydel")
                        .HasColumnType("int");

                    b.Property<float>("JednostkiOkienDoPoz")
                        .HasColumnType("real");

                    b.Property<float>("JednostkiOkienDoPozZrobione")
                        .HasColumnType("real");

                    b.Property<float>("JednostkiOkienSumaDoPoz")
                        .HasColumnType("real");

                    b.Property<string>("Kolor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Nr")
                        .HasColumnType("real");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdLiniiProdukcyjnej")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZlecenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("System")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Szerokosc")
                        .HasColumnType("real");

                    b.Property<string>("Szyba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Wysokosc")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PozDoZlecen");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.Pracownicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Autorzmiany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datautowrzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dzial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasloDoPoczty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasloSQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kodkreskowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Nieaktywny")
                        .HasColumnType("bit");

                    b.Property<string>("Notatka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdDzialu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stanowisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StanowiskoSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UzytkownikSQL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.ProducenciPodwykonawcy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresWWW1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresWWW2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailOsobyKontaktowej1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailOsobyKontaktowej2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailOsobyKontaktowej3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailOsobyKontaktowej4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailOsobyKontaktowej5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IloscDniRealizacji")
                        .HasColumnType("int");

                    b.Property<bool>("KlienetWymagaProforma")
                        .HasColumnType("bit");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProducenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsobaKontaktowa1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsobaKontaktowa2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsobaKontaktowa3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsobaKontaktowa4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsobaKontaktowa5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajProdukcjiWykonywanej")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonOsobyKontaktowej1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonOsobyKontaktowej2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonOsobyKontaktowej3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonOsobyKontaktowej4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonOsobyKontaktowej5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProducenciPodwykonawcy");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.RodzajeDzialow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autorzmiany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datautowrzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazwaDzialu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notatka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RodzajeDzialow");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.RodzajeKartInstrukcyjnych", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerRodzajuKart")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OpisRodzajuKart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NumerRodzajuKart")
                        .IsUnique()
                        .HasFilter("[NumerRodzajuKart] IS NOT NULL");

                    b.ToTable("RodzajeKartInstrukcyjnych");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.SystemyOkienne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa_Systemu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis_Systemu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Wycofany_z_produkcji")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SystemyOkienne");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.SzybyDoZlecen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CzyKsztalt")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZamowiono")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataDostarczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("IloscSztuk")
                        .HasColumnType("int");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PozDostarczono")
                        .HasColumnType("bit");

                    b.Property<string>("RodzajRamki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajSzyby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZlecenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Szerokosc")
                        .HasColumnType("real");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Wysokosc")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SzybyDoZlecen");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.Uprawnieniapracownika", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Administrator")
                        .HasColumnType("bit");

                    b.Property<string>("Autorzmiany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datautowrzenia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Odczyt")
                        .HasColumnType("bit");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdPracownicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdRejestrejestrow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Usuniecie")
                        .HasColumnType("bit");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Zapis")
                        .HasColumnType("bit");

                    b.Property<bool>("Zmiana")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Uprawnieniapracownika");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.ZleceniaCzasNaLinieProd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CzasNaZlecenie")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdLinieProdukcyjne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZleceniaProdukcyjne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ZlecenieWewnetrzne")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZleceniaCzasNaLinieProd");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.ZleceniaNaLinii", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRozpProdukcjiNaLinii")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdLinieProdukcyjne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZleceniaProdukcyjne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ZlecenieWewnetrzne")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZleceniaNaLinii");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.ZleceniaProdukcyjne", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataGotowosci")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMontazu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProdukcji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRozpProdukcji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWysylki")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<float>("JednostkiNaZlecenie")
                        .HasColumnType("real");

                    b.Property<string>("Klient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerUmowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerZamowienia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerZlecenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcentWykonania")
                        .HasColumnType("int");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypZamowienia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Wartosc")
                        .HasColumnType("real");

                    b.Property<bool>("ZlecZrealizowane")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZleceniaProdukcyjne");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.ZleceniaProdukcyjneWew", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataGotowosci")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMontazu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProdukcji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRozpProdukcji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWysylki")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<float>("JednostkiNaZlecenie")
                        .HasColumnType("real");

                    b.Property<string>("Klient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerUmowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerZamowienia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerZlecenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcentWykonania")
                        .HasColumnType("int");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypZamowienia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Wartosc")
                        .HasColumnType("real");

                    b.Property<bool>("ZlecZrealizowane")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZleceniaProdukcyjneWew");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.ZleceniaProdukcyjneZmianyStatusu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataGotowosci")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMontazu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProdukcji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRozpProdukcji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWysylki")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<float>("JednostkiNaZlecenie")
                        .HasColumnType("real");

                    b.Property<string>("Klient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerUmowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerZamowienia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerZlecenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZlecenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypZamowienia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Wartosc")
                        .HasColumnType("real");

                    b.Property<bool>("ZlecenieWewnatrzne")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZleceniaProdukcyjneZmianyStatusu");
                });
#pragma warning restore 612, 618
        }
    }
}
