// <auto-generated />
using System;
using GEORGE.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GEORGE.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GEORGE.Shared.Models.KartyInstrukcyjne", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("IloscStron")
                        .HasColumnType("int");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkDoKartyNaSerwerze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerKarty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisKarty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KartyInstrukcyjne");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.PlikiZlecenProdukcyjnych", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowIdZleceniaProdukcyjne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypPliku")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlikiZlecenProdukcyjnych");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.RodzajeKartInstrukcyjnych", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerRodzajuKart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisRodzajuKart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RodzajeKartInstrukcyjnych");
                });

            modelBuilder.Entity("GEORGE.Shared.Models.ZleceniaProdukcyjne", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataMontazu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProdukcji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWysylki")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<string>("Klient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtoZapisal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProduktu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerUmowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerZamowienia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OstatniaZmiana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Wartosc")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ZleceniaProdukcyjne");
                });
#pragma warning restore 612, 618
        }
    }
}
